#!/usr/bin/env python3
"""Generate human-readable reports from authoritative VSTest TRX results.

The pass/fail state comes only from UnitTestResult outcome values written by
'dotnet test'. Console/logger text such as "PASS" never changes the result.
"""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path
import xml.etree.ElementTree as ET


def local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def duration_seconds(value: str | None) -> float:
    if not value:
        return 0.0
    try:
        parts = value.split(":")
        if len(parts) != 3:
            return 0.0
        return float(parts[0]) * 3600 + float(parts[1]) * 60 + float(parts[2])
    except ValueError:
        return 0.0


def child_text(result: ET.Element, *path: str) -> str:
    node = result
    for name in path:
        found = next((c for c in node if local_name(c.tag) == name), None)
        if found is None:
            return ""
        node = found
    return (node.text or "").strip()


def parse_trx(path: Path) -> list[dict[str, object]]:
    root = ET.parse(path).getroot()
    rows: list[dict[str, object]] = []

    for element in root.iter():
        if local_name(element.tag) != "UnitTestResult":
            continue

        outcome = element.attrib.get("outcome", "Unknown")
        rows.append(
            {
                "source": path.name,
                "name": element.attrib.get("testName", "Unnamed test"),
                "outcome": outcome,
                "duration": duration_seconds(element.attrib.get("duration")),
                "message": child_text(element, "Output", "ErrorInfo", "Message"),
                "stack": child_text(element, "Output", "ErrorInfo", "StackTrace"),
                "stdout": child_text(element, "Output", "StdOut"),
            }
        )

    return rows


def outcome_group(outcome: str) -> str:
    value = outcome.casefold()
    if value == "passed":
        return "passed"
    if value in {"failed", "error", "timeout", "aborted"}:
        return "failed"
    if value in {"notexecuted", "skipped", "inconclusive"}:
        return "skipped"
    return "other"


def write_markdown(rows: list[dict[str, object]], destination: Path) -> None:
    counts = {"passed": 0, "failed": 0, "skipped": 0, "other": 0}
    for row in rows:
        counts[outcome_group(str(row["outcome"]))] += 1

    total = len(rows)
    duration = sum(float(row["duration"]) for row in rows)
    lines = [
        "## NUnit / Playwright test result",
        "",
        "> Source of truth: VSTest TRX generated by dotnet test. "
        "Application log messages cannot mark a failed NUnit test as passed.",
        "",
        f"**Total:** {total}  |  **Passed:** {counts['passed']}  |  "
        f"**Failed:** {counts['failed']}  |  **Skipped:** {counts['skipped']}  |  "
        f"**Duration:** {duration:.2f}s",
        "",
    ]

    failed = [row for row in rows if outcome_group(str(row["outcome"])) == "failed"]
    if failed:
        lines.extend(["### Failed tests", "", "| Test | Outcome | Duration |", "|---|---|---:|"])
        for row in failed:
            name = str(row["name"]).replace("|", "\\|")
            lines.append(f"| {name} | {row['outcome']} | {float(row['duration']):.2f}s |")
    else:
        lines.append("✅ No failed tests were recorded in the TRX result.")

    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_html(rows: list[dict[str, object]], destination: Path) -> None:
    counts = {"passed": 0, "failed": 0, "skipped": 0, "other": 0}
    for row in rows:
        counts[outcome_group(str(row["outcome"]))] += 1

    total = len(rows)
    duration = sum(float(row["duration"]) for row in rows)

    table_rows: list[str] = []
    for row in sorted(rows, key=lambda r: (outcome_group(str(r["outcome"])) != "failed", str(r["name"]))):
        group = outcome_group(str(row["outcome"]))
        details_parts = []
        if row["message"]:
            details_parts.append(f"<strong>Message</strong><pre>{html.escape(str(row['message']))}</pre>")
        if row["stack"]:
            details_parts.append(f"<strong>Stack trace</strong><pre>{html.escape(str(row['stack']))}</pre>")
        if row["stdout"]:
            details_parts.append(f"<strong>Output</strong><pre>{html.escape(str(row['stdout']))}</pre>")
        details = "".join(details_parts) or "—"

        table_rows.append(
            "<tr>"
            f"<td>{html.escape(str(row['name']))}</td>"
            f"<td><span class=\"badge {group}\">{html.escape(str(row['outcome']))}</span></td>"
            f"<td>{float(row['duration']):.2f}s</td>"
            f"<td>{html.escape(str(row['source']))}</td>"
            f"<td><details><summary>View</summary>{details}</details></td>"
            "</tr>"
        )

    document = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tedile Automation Test Report</title>
<style>
body {{ font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; margin: 32px; color: #1f2328; }}
h1 {{ margin-bottom: 6px; }}
.note {{ padding: 12px 16px; background: #f6f8fa; border-left: 4px solid #57606a; margin: 18px 0; }}
.cards {{ display: flex; gap: 12px; flex-wrap: wrap; margin: 20px 0; }}
.card {{ border: 1px solid #d0d7de; border-radius: 8px; padding: 12px 18px; min-width: 110px; }}
.card strong {{ display: block; font-size: 24px; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
th, td {{ border: 1px solid #d0d7de; padding: 9px; text-align: left; vertical-align: top; }}
th {{ background: #f6f8fa; }}
.badge {{ font-weight: 700; }}
.passed {{ color: #1a7f37; }}
.failed {{ color: #cf222e; }}
.skipped, .other {{ color: #9a6700; }}
pre {{ white-space: pre-wrap; word-break: break-word; max-width: 900px; }}
</style>
</head>
<body>
<h1>Tedile Automation Test Report</h1>
<div class="note"><strong>Authoritative result source:</strong> VSTest TRX generated by <code>dotnet test</code>.
A manually printed <code>PASS</code> message cannot change an NUnit failure into a pass.</div>
<div class="cards">
<div class="card">Total<strong>{total}</strong></div>
<div class="card">Passed<strong>{counts['passed']}</strong></div>
<div class="card">Failed<strong>{counts['failed']}</strong></div>
<div class="card">Skipped<strong>{counts['skipped']}</strong></div>
<div class="card">Duration<strong>{duration:.2f}s</strong></div>
</div>
<table>
<thead><tr><th>Test</th><th>Result</th><th>Duration</th><th>TRX</th><th>Failure / output details</th></tr></thead>
<tbody>
{''.join(table_rows)}
</tbody>
</table>
</body>
</html>
"""
    destination.write_text(document, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("results_dir", type=Path)
    parser.add_argument("--html", dest="html_path", type=Path, required=True)
    parser.add_argument("--markdown", dest="markdown_path", type=Path, required=True)
    args = parser.parse_args()

    trx_files = sorted(args.results_dir.rglob("*.trx"))
    if not trx_files:
        print(f"No TRX files found under {args.results_dir}", file=sys.stderr)
        return 2

    rows: list[dict[str, object]] = []
    for trx in trx_files:
        rows.extend(parse_trx(trx))

    if not rows:
        print("TRX files were found but contained no UnitTestResult entries.", file=sys.stderr)
        return 3

    args.html_path.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_path.parent.mkdir(parents=True, exist_ok=True)
    write_html(rows, args.html_path)
    write_markdown(rows, args.markdown_path)
    print(f"Generated {args.html_path} and {args.markdown_path} from {len(rows)} test results.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
